updated docker config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,10 +43,16 @@ jobs:
           name: Docker Login
           command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
       - run:
-          name: Build Docker Image
+          name: Build and Tag Docker Image
           command: |
             docker build -t $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 . --verbose
             docker tag $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 $DOCKER_USER/circleci_m4:latest
+            build_status=$?  # Capture build command exit status
+            echo "Docker build exit status: $build_status"
+            docker tag $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 $DOCKER_USER/circleci_m4:latest
+            tag_status=$?  # Capture tag command exit status
+            echo "Docker tag exit status: $tag_status"
+            exit $(($build_status + $tag_status))  # Exit with combined status of build and tag
       - run:
           name: Push Docker Image
           command: |
