updated docker config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -47,20 +47,29 @@ jobs:
 
   # Build and Push job
   build-and-push:
-    executor: docker/docker
+    docker:
+      - image: cimg/base:stable
     steps:
       - checkout
-      - docker/check:
-          registry-url: https://index.docker.io/v1/
-      - docker/build:
-          image: "circleci_m4"
-          tag: "${CIRCLE_SHA1},latest"
-          registry-url: https://index.docker.io/v1/
-          dockerfile: Dockerfile
-      - docker/push:
-          image: "circleci_m4"
-          tag: "${CIRCLE_SHA1},latest"
-          registry-url: https://index.docker.io/v1/
+      - run:
+          name: Docker Login
+          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
+      - run:
+          name: Build and Tag Docker Image
+          command: |
+            docker build -t $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 . -v
+            docker tag $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 $DOCKER_USER/circleci_m4:latest
+            build_status=$?  # Capture build command exit status
+            echo "Docker build exit status: $build_status"
+            docker tag $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 $DOCKER_USER/circleci_m4:latest
+            tag_status=$?  # Capture tag command exit status
+            echo "Docker tag exit status: $tag_status"
+            exit $(($build_status + $tag_status))  # Exit with combined status of build and tag
+      - run:
+          name: Push Docker Image
+          command: |
+            docker push $DOCKER_USER/circleci_m4:$CIRCLE_SHA1
+            docker push $DOCKER_USER/circleci_m4:latest
 
   # Check Docker job
   check-docker:
@@ -79,7 +88,6 @@ workflows:
   version: 2
   simple_workflow:
     jobs:
-      - build-and-push
       - build
       - test:
           requires:
