updated docker config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,9 +20,18 @@ jobs:
       - run:
           name: Install Dependencies
           command: npm install
-      - run:
-          name: Docker Build
-          command: docker build -t $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 .
+      # - run:
+      #     name: Check Docker Daemon Status
+      #     command: sudo systemctl status docker
+      # - run:
+      #     name: Restart Docker Service
+      #     command: sudo systemctl restart docker
+      # - run:
+      #     name: Check Docker Socket Permissions
+      #     command: ls -l /var/run/docker.sock
+      # - run:
+      #     name: Docker Build
+      #     command: docker build -t $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 .
 
   # Test job
   test:
@@ -39,23 +48,28 @@ jobs:
   # Build and Push job
   build-and-push:
     docker:
-      - image: cimg/go:1.17
+      - image: cimg/base:stable
     steps:
       - checkout
-      - node/install-packages:
-          pkg-manager: npm
       - run:
-          name: Install Dependencies
-          command: npm install
-      - setup_remote_docker:
-          docker_layer_caching: true
+          name: Docker Login
+          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
       - run:
-          name: Docker Build and Push
+          name: Build and Tag Docker Image
           command: |
-            TAG=0.1.$CIRCLE_BUILD_NUM
-            docker build -t $DOCKER_USER/circleci-demo-docker:$TAG .
-            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
-            docker push $DOCKER_USER/circleci-demo-docker:$TAG
+            docker build -t $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 .
+            docker tag $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 $DOCKER_USER/circleci_m4:latest
+            build_status=$?  # Capture build command exit status
+            echo "Docker build exit status: $build_status"
+            docker tag $DOCKER_USER/circleci_m4:$CIRCLE_SHA1 $DOCKER_USER/circleci_m4:latest
+            tag_status=$?  # Capture tag command exit status
+            echo "Docker tag exit status: $tag_status"
+            exit $(($build_status + $tag_status))  # Exit with combined status of build and tag
+      - run:
+          name: Push Docker Image
+          command: |
+            docker push $DOCKER_USER/circleci_m4:$CIRCLE_SHA1
+            docker push $DOCKER_USER/circleci_m4:latest
 
   # Check Docker job
   check-docker:
